/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Store = IDL.Record({
  'city' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Price = IDL.Nat;
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isDeal' : IDL.Bool,
  'stock' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'price' : Price,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'products' : IDL.Vec(Product),
  'totalPrice' : Price,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStore' : IDL.Func([Store], [IDL.Nat], []),
  'addToCallerCart' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkoutCallerCart' : IDL.Func([], [], []),
  'clearCallerCart' : IDL.Func([], [], []),
  'createProduct' : IDL.Func([Product], [IDL.Nat], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteStore' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
  'getCallerCart' : IDL.Func([], [IDL.Vec(Product)], []),
  'getCallerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDealProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductPagination' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getSearchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getSearchProductsPagination' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([], [IDL.Nat], []),
  'removeFromCallerCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'updateStore' : IDL.Func([IDL.Nat, Store], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Store = IDL.Record({
    'city' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Price = IDL.Nat;
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isDeal' : IDL.Bool,
    'stock' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'price' : Price,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'products' : IDL.Vec(Product),
    'totalPrice' : Price,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStore' : IDL.Func([Store], [IDL.Nat], []),
    'addToCallerCart' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkoutCallerCart' : IDL.Func([], [], []),
    'clearCallerCart' : IDL.Func([], [], []),
    'createProduct' : IDL.Func([Product], [IDL.Nat], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteStore' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
    'getCallerCart' : IDL.Func([], [IDL.Vec(Product)], []),
    'getCallerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDealProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductPagination' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSearchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getSearchProductsPagination' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([], [IDL.Nat], []),
    'removeFromCallerCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'updateStore' : IDL.Func([IDL.Nat, Store], [], []),
  });
};

export const init = ({ IDL }) => { return []; };